#pragma config(Motor,  port1,           Left,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          Right,         tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true)
	{
		motor[Left] = vexRT[Ch3];	 // Set the left side wheel(s) to the value from channel 3 of the joystick
		motor[Right] = vexRT[Ch2];	 // Set the right side wheel(s) to the value from channel 2 of the joystick
	}
}
