#pragma config(Motor,  port1,           Left,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          Right,         tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true)
	{
		motor[Left] = vexRT[Ch2] + vexRT[Ch1];
		motor[Right] = vexRT[Ch2] - vexRT[Ch1];
	}
}
