#pragma config(Motor,  port1,           Left,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           Steering,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          Right,         tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true)
	{
		// Button 7L for strafing left
		// Button 8R for strafing right
		// Right joystick for normal drive
		if (vexRT[Btn7L] == 1) // Button 7L for strafing left
		{
			motor[Left] = 0;
			motor[Right] = 0; // Stop other motors
			motor[Steering] = -127; // Go left
		}
		else if (vexRT[Btn8R] == 1)
		{
			motor[Left] = 0;
			motor[Right] = 0; // Stop other motors
			motor[Steering] = 127; // Go right
		}
		else
		{
			motor[Left] = vexRT[Ch2] + vexRT[Ch1];
			motor[Right] = vexRT[Ch2] - vexRT[Ch1]; // Single joystick drive code
			motor[Steering] = vexRT[Ch1];
		}
	}
}
