#pragma config(Motor,  port1,           Left,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           Steering,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          Right,         tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
	while (true)
	{
		// Left horizontal joystick for strafing
	  // Right joystick: vertical for back and forth motion
	  //                 horizontal for turning

		if ( abs(vexRT[Ch4]) > 15)
		{
			motor[Left] = 0;
			motor[Right] = 0;
			motor[Steering] = vexRT[Ch4];
		}
		else
		{
			motor[Left] = vexRT[Ch2] + vexRT[Ch1];
			motor[Right] = vexRT[Ch2] - vexRT[Ch1]; // Single joystick drive code
			motor[Steering] = vexRT[Ch1];
		}

	}
}
