#pragma config(Sensor, dgtl1,  Button,         sensorTouch)
#pragma config(Motor,  port1,           motor1,        tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          motor2,        tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	/*
	motor[motor1] = motor[motor2] = 127; // What it is doing
	wait1Msec(1000);     // For how long
	*/

	while (true) // Repeat what's inside it forever
	{
		if (SensorValue[Button] == 1) // Check if the button is pressed. Run the following if yes.
		{
			motor[motor1] = motor[motor2] = 127;
			// You don't need to specify time again, since the if loop serves as the time.
		}
		else // If not... Run the following
		{
			motor[motor1] = motor[motor2] = 0;
		}
	}
}
